name: CI for MWAA
on:
 push:
 env:
	  BUCKET_NAME : "<your-mwaa-bucket-name>"
	  AWS_REGION : "<example-aws-region>"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
       
               	

	

